language: python
sudo: required
dist: xenial
group: travis_latest

git:
  depth: 3
  quiet: true

python:
- 3.7
- 3.6
- 3.5

os:
- linux

install: pip install -e .[tests]

script:
- pytest -rsv
#- flake8
# - mypy . --ignore-missing-imports

after_success:
- if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
  pytest --cov --cov-config=setup.cfg;
  coveralls;
  fi

deploy:
  provider: pypi
  user: dstansby
  password:
    secure: GrlqVedIuT9cFhb9DYHYcqmmIrI2YstN0u9CeB18oROxpV5z2Sz0M+mggER2htYPFo9LdKqYlSkJ9DqrzlJtdbr/lOFlesugedg3GQSc3O+D5wCigERrpnciqFuNqi8Za9fZFSsE8oNzpa+ymiewcmOT00KgfCdxutPLXGkkk3CoKS/pt7mSqzsPfN0WNAN7Hwn0tvMvqOagVbPPkcgsnR23U5K9pB9wsqLkIw6ubFg8wK597Vc/NymydSJLDdXw1n8bL+DKJtCvNUQOhH6qUKdk5/tEuLhrYMQxp2dE7w2ntSKh8bbmIGqf+MCGHBAHIDsIwyqx7l+D99oka4BPvWZPIS/FLdsgbQdNQNgvkXuviE9AmleEnQp/kbddtQRi2yye50LvuTPoMleFEN3aoZl/0GuwmIR9msKcB+/fcYLXlg27nOq6ZqSXn2FCs1IfXubppUMWqVrgTtzBpaPkqfqMN1tV2+fbfWK3w3u7/iiZgPcyltju80Pi2iXi6c/TEuT+8y3369skVCILTB1Ei4ay4otnGfk0D6KNTRLwv/X0q8rrY/IMnkmiBuv48m2pEyHbICnzHHxgJP8gSJqeTQI4gRC86VHlUckPSZNtKtZYed/810PLa2EVwO/yHNxTv1K39f0NeHsb43q8jN0OA5RRBZC22PWIYrgCgyNAKWY=
  on:
    tags: true
