name: ci

on: [push, pull_request]

jobs:

  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - run: pip install .[tests]
    - run: pytest --cov --tb=long
    - uses: codecov/codecov-action@v2
